### ISSUE TITLE
Start setting up and familiarizing yourself with the platform

### ISSUE THREAD

**Issue by nxchotakuu** [Allen-ISD-Computer-Science/REPO_FoodGame_2024#3]

**Comment by NathanK1025** [comment]
I have set up Roblox Studio and we have created a project that everyone can work on in Roblox Studio.

**Comment by SV0508** [comment]
I have set up and downloaded Roblox studio on my laptop and spent time learning the new features. I have also done work into importing files for the designs/ graphics.
